// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 85TuUS2HqupE65YrWAJYno
// Component: elg-uBlVH3
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_2_xcell_landing_page.module.css"; // plasmic-import: 85TuUS2HqupE65YrWAJYno/projectcss
import * as sty from "./PlasmicLandingPage.module.css"; // plasmic-import: elg-uBlVH3/css

import Group3Icon from "./icons/PlasmicIcon__Group3"; // plasmic-import: iYK_bKALqA/icon
import Path1102Icon from "./icons/PlasmicIcon__Path1102"; // plasmic-import: EF7P-P4dj2/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: NnPllos6v/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: l9LUKo7KNvi/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: ZA7sK3fqDy8/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: RU2SKHE3qlN/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: N7xjy0zQWz_/icon
import GroupIcon from "./icons/PlasmicIcon__Group"; // plasmic-import: 0zjxkzAV20u/icon
import Rectangle4Icon from "./icons/PlasmicIcon__Rectangle4"; // plasmic-import: YzRNGHdyvf1/icon
import Rectangle3Icon from "./icons/PlasmicIcon__Rectangle3"; // plasmic-import: Su7kw5V9hzl/icon
import Rectangle2Icon from "./icons/PlasmicIcon__Rectangle2"; // plasmic-import: bItsBHba2E/icon
import Polygon2Icon from "./icons/PlasmicIcon__Polygon2"; // plasmic-import: R8P6XZYBnV/icon
import Rectangle7Icon from "./icons/PlasmicIcon__Rectangle7"; // plasmic-import: vADipQr7JP/icon
import Rectangle1519Icon from "./icons/PlasmicIcon__Rectangle1519"; // plasmic-import: sY2v-i0_WWt/icon
import Rectangle10Icon from "./icons/PlasmicIcon__Rectangle10"; // plasmic-import: qXTePfCoi0Q/icon
import Rectangle8Icon from "./icons/PlasmicIcon__Rectangle8"; // plasmic-import: j8ggNEtMbP/icon
import Rectangle9Icon from "./icons/PlasmicIcon__Rectangle9"; // plasmic-import: 7AvNOgXN37/icon
import Ellipse2Icon from "./icons/PlasmicIcon__Ellipse2"; // plasmic-import: MqqNg7auKB/icon
import Polygon1Icon from "./icons/PlasmicIcon__Polygon1"; // plasmic-import: mEAw-TW7YKe/icon
import Rectangle1575Icon from "./icons/PlasmicIcon__Rectangle1575"; // plasmic-import: rgtbv8gVf3/icon
import Rectangle1576Icon from "./icons/PlasmicIcon__Rectangle1576"; // plasmic-import: ny2jtBcUjx/icon
import Rectangle11Icon from "./icons/PlasmicIcon__Rectangle11"; // plasmic-import: pDx-6gcR38k/icon
import Rectangle1577Icon from "./icons/PlasmicIcon__Rectangle1577"; // plasmic-import: 5AmfjJmivvm/icon
import Rectangle1578Icon from "./icons/PlasmicIcon__Rectangle1578"; // plasmic-import: av0KNMlr81/icon
import Line207Icon from "./icons/PlasmicIcon__Line207"; // plasmic-import: UWPmpvyZlI/icon

export type PlasmicLandingPage__VariantMembers = {};

export type PlasmicLandingPage__VariantsArgs = {};
type VariantPropType = keyof PlasmicLandingPage__VariantsArgs;
export const PlasmicLandingPage__VariantProps = new Array<VariantPropType>();

export type PlasmicLandingPage__ArgsType = {};
type ArgPropType = keyof PlasmicLandingPage__ArgsType;
export const PlasmicLandingPage__ArgProps = new Array<ArgPropType>();

export type PlasmicLandingPage__OverridesType = {
  root?: p.Flex<"div">;
  navBar?: p.Flex<"nav">;
  navContent?: p.Flex<"div">;
  logo?: p.Flex<"img">;
  navLinks?: p.Flex<"div">;
  home?: p.Flex<"div">;
  contactUs?: p.Flex<"div">;
  blog?: p.Flex<"div">;
  _2XCellForStudents?: p.Flex<"div">;
  demo?: p.Flex<"div">;
  mainContent?: p.Flex<"main">;
  heroContent?: p.Flex<"div">;
  illustration?: p.Flex<"div">;
  group3?: p.Flex<"div">;
  why2Xcell?: p.Flex<"div">;
  why2XcellContent?: p.Flex<"div">;
  btn?: p.Flex<"button">;
  btn2?: p.Flex<"div">;
  aboutSection?: p.Flex<"div">;
  aboutContent?: p.Flex<"div">;
  btn3?: p.Flex<"div">;
  image6?: p.Flex<"div">;
  strengthSection?: p.Flex<"div">;
  strengthContent?: p.Flex<"div">;
  group914?: p.Flex<"div">;
  _1?: p.Flex<"div">;
  _2?: p.Flex<"div">;
  _4?: p.Flex<"div">;
  _3?: p.Flex<"div">;
  studentSection?: p.Flex<"div">;
  studentContent?: p.Flex<"div">;
  browseCourses?: p.Flex<"div">;
  time?: p.Flex<"div">;
  time2?: p.Flex<"div">;
  maskGroup1?: p.Flex<"div">;
  time3?: p.Flex<"div">;
  grade1?: p.Flex<"div">;
  grade2?: p.Flex<"div">;
  grade3?: p.Flex<"div">;
  palyIcon?: p.Flex<"div">;
  palyIcon2?: p.Flex<"div">;
  image7?: p.Flex<"div">;
  footer?: p.Flex<"footer">;
  footerContent?: p.Flex<"div">;
  commuinity?: p.Flex<"div">;
  joinUs?: p.Flex<"div">;
  studentSchoolsContactUsCareer?: p.Flex<"div">;
  group926?: p.Flex<"div">;
  group927?: p.Flex<"div">;
  instagramLogoPng6023F9Ae0Feb9680X680?: p.Flex<"div">;
  socialLinkedinCircle512?: p.Flex<"div">;
  image8?: p.Flex<"div">;
};

export interface DefaultLandingPageProps {
  dataFetches: PlasmicLandingPage__Fetches;
}

function PlasmicLandingPage__RenderFunc(props: {
  variants: PlasmicLandingPage__VariantsArgs;
  args: PlasmicLandingPage__ArgsType;
  overrides: PlasmicLandingPage__OverridesType;
  dataFetches?: PlasmicLandingPage__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <React.Fragment>
      <Head>
        <title key="title">{""}</title>
        <meta key="og:title" property="og:title" content={""} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={""}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <nav
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames(defaultcss.all, sty.navBar)}
          >
            <div
              data-plasmic-name={"navContent"}
              data-plasmic-override={overrides.navContent}
              className={classNames(defaultcss.all, sty.navContent)}
            >
              <img
                data-plasmic-name={"logo"}
                data-plasmic-override={overrides.logo}
                alt={""}
                className={classNames(defaultcss.img, sty.logo)}
                role={"img"}
                src={"https://www.2xcell.in/images/logo/logo_2x.png" as const}
              />

              <div
                data-plasmic-name={"navLinks"}
                data-plasmic-override={overrides.navLinks}
                className={classNames(defaultcss.all, sty.navLinks)}
              >
                <div
                  data-plasmic-name={"home"}
                  data-plasmic-override={overrides.home}
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.home
                  )}
                >
                  {"Home                "}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__upe1H
                  )}
                >
                  {"About"}
                </div>

                <div
                  data-plasmic-name={"contactUs"}
                  data-plasmic-override={overrides.contactUs}
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.contactUs
                  )}
                >
                  {"Contact Us "}
                </div>

                <div
                  data-plasmic-name={"blog"}
                  data-plasmic-override={overrides.blog}
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.blog
                  )}
                >
                  {"Blog "}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__yLjb0
                  )}
                >
                  {"Login"}
                </div>

                <div
                  data-plasmic-name={"_2XCellForStudents"}
                  data-plasmic-override={overrides._2XCellForStudents}
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty._2XCellForStudents
                  )}
                >
                  {"2xCell for Students "}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__dgPvt
                  )}
                >
                  {"2xCell for Schools"}
                </div>

                <div
                  data-plasmic-name={"demo"}
                  data-plasmic-override={overrides.demo}
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.demo
                  )}
                >
                  {" Demo"}
                </div>
              </div>
            </div>
          </nav>

          <main
            data-plasmic-name={"mainContent"}
            data-plasmic-override={overrides.mainContent}
            className={classNames(defaultcss.all, sty.mainContent)}
          >
            <div
              data-plasmic-name={"heroContent"}
              data-plasmic-override={overrides.heroContent}
              className={classNames(defaultcss.all, sty.heroContent)}
            >
              <div
                data-plasmic-name={"illustration"}
                data-plasmic-override={overrides.illustration}
                className={classNames(defaultcss.all, sty.illustration)}
              >
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__bFmix)}
                  role={"img"}
                  src={"/plasmic/2_xcell_landing_page/images/elementsCopy2.svg"}
                />

                <div
                  data-plasmic-name={"group3"}
                  data-plasmic-override={overrides.group3}
                  className={classNames(defaultcss.all, sty.group3)}
                >
                  <Group3Icon
                    className={classNames(defaultcss.all, sty.svg__jKvJn)}
                    role={"img"}
                  />
                </div>

                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__hSbi)}
                  role={"img"}
                  src={"/plasmic/2_xcell_landing_page/images/group79.svg"}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__oevto
                )}
              >
                {"Personalized Online \nLearning Classes"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__ox4UE
                )}
              >
                {
                  "Help your child discover his true potential \nwith AI based learning."
                }
              </div>

              <Path1102Icon
                className={classNames(defaultcss.all, sty.svg__m5DB7)}
                role={"img"}
              />
            </div>

            <div
              data-plasmic-name={"why2Xcell"}
              data-plasmic-override={overrides.why2Xcell}
              className={classNames(defaultcss.all, sty.why2Xcell)}
            >
              <div
                data-plasmic-name={"why2XcellContent"}
                data-plasmic-override={overrides.why2XcellContent}
                className={classNames(defaultcss.all, sty.why2XcellContent)}
              >
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__ho7M4)}
                  role={"img"}
                  src={"/plasmic/2_xcell_landing_page/images/rectangle6.svg"}
                />

                <Icon5Icon
                  className={classNames(defaultcss.all, sty.svg__uoqGq)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__cWrV
                  )}
                >
                  {"Experienced &\nHighly Qualified\nFaculty"}
                </div>

                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__rRatT)}
                  role={"img"}
                  src={"/plasmic/2_xcell_landing_page/images/rectangle6.svg"}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox___5WsjO
                  )}
                >
                  {"Power-packed \nresource library"}
                </div>

                <Icon4Icon
                  className={classNames(defaultcss.all, sty.svg__liWoq)}
                  role={"img"}
                />

                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__pJwKo)}
                  role={"img"}
                  src={"/plasmic/2_xcell_landing_page/images/rectangle6.svg"}
                />

                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__uaquv)}
                  role={"img"}
                  src={"/plasmic/2_xcell_landing_page/images/rectangle6.svg"}
                />

                <Icon3Icon
                  className={classNames(defaultcss.all, sty.svg__iAccl)}
                  role={"img"}
                />

                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__rf70C)}
                  role={"img"}
                  src={"/plasmic/2_xcell_landing_page/images/rectangle6.svg"}
                />

                <Icon2Icon
                  className={classNames(defaultcss.all, sty.svg__kYxV)}
                  role={"img"}
                />

                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__vBSn3)}
                  role={"img"}
                  src={"/plasmic/2_xcell_landing_page/images/rectangle6.svg"}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__crM6X
                  )}
                >
                  {
                    "A.I driven analytics \nthat suggests \ntheright Learning path"
                  }
                </div>

                <IconIcon
                  className={classNames(defaultcss.all, sty.svg__sxfS)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox___8T2Bs
                  )}
                >
                  {"Why 2Xcell?"}
                </div>

                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__uLk9M)}
                  role={"img"}
                  src={"/plasmic/2_xcell_landing_page/images/rectangle161.svg"}
                />

                <button
                  data-plasmic-name={"btn"}
                  data-plasmic-override={overrides.btn}
                  className={classNames(defaultcss.button, sty.btn)}
                >
                  <GroupIcon
                    className={classNames(defaultcss.all, sty.svg__oazkV)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__dgj2C
                    )}
                  >
                    {"Register Now"}
                  </div>
                </button>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__qeRGo
                  )}
                >
                  {"Your excellence, our commitment!"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__hQ8J4
                  )}
                >
                  {"Please provide require details"}
                </div>

                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__pcKwl)}
                  role={"img"}
                  src={"/plasmic/2_xcell_landing_page/images/rectangle5.svg"}
                />

                <Rectangle4Icon
                  className={classNames(defaultcss.all, sty.svg__rCf)}
                  role={"img"}
                />

                <Rectangle4Icon
                  className={classNames(defaultcss.all, sty.svg__mJWpZ)}
                  role={"img"}
                />

                <Rectangle3Icon
                  className={classNames(defaultcss.all, sty.svg__nXn8O)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__mfMhB
                  )}
                >
                  {"Name of your Child"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox___8QkzK
                  )}
                >
                  {"Mobile Number"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__dWy
                  )}
                >
                  {"Email Address"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__cCkAy
                  )}
                >
                  {"State"}
                </div>

                <div
                  data-plasmic-name={"btn2"}
                  data-plasmic-override={overrides.btn2}
                  className={classNames(defaultcss.all, sty.btn2)}
                >
                  <Rectangle2Icon
                    className={classNames(defaultcss.all, sty.svg__ktPF)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__ebL9L
                    )}
                  >
                    {"Send OTP"}
                  </div>
                </div>

                <Polygon2Icon
                  className={classNames(defaultcss.all, sty.svg__ggDhf)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__msd8R
                  )}
                >
                  {"Best student - \nteacher match \nbased on Analytics"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__n7Gt4
                  )}
                >
                  {"Most innovative\ndoubt section"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__vmOzw
                  )}
                >
                  {"24x7 Support"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__ys3Ba
                  )}
                >
                  {"?"}
                </div>
              </div>
            </div>

            <div
              data-plasmic-name={"aboutSection"}
              data-plasmic-override={overrides.aboutSection}
              className={classNames(defaultcss.all, sty.aboutSection)}
            >
              <div
                data-plasmic-name={"aboutContent"}
                data-plasmic-override={overrides.aboutContent}
                className={classNames(defaultcss.all, sty.aboutContent)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__yTwyL
                  )}
                >
                  {"About Us"}
                </div>

                <div
                  data-plasmic-name={"btn3"}
                  data-plasmic-override={overrides.btn3}
                  className={classNames(defaultcss.all, sty.btn3)}
                >
                  <Rectangle7Icon
                    className={classNames(defaultcss.all, sty.svg__ma8FY)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__iPKzI
                    )}
                  >
                    {"Read More"}
                  </div>
                </div>

                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__zi2Cy)}
                  role={"img"}
                  src={"/plasmic/2_xcell_landing_page/images/image.svg"}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__mAePu
                  )}
                >
                  {
                    "2Xcell is an A.I driven self-paced learning\n and online education platform that helps a student\n become a ‘Super Learner’ using\n Blended Learning Model. Students get “Exclusive Personalized \nLearning Experience” where they are guided by \n“Dedicated Mentor” which strengthens the\n learning base of students and helps them learn\n in online courses through customized interactive \n3D-2D videos at a much faster pace.\nInquiry-Based Learning (IBL) helps a student \nassess himself and measure the learning outcome \n/ Learning index or Lx at subtopic level and provides\n remarkable insights to help mentor plan the right \npedagogy for the student and design a personalized\n ‘Goal Oriented’ learning plan. Seamless integration of \nconcepts across grades under the “Multi-Grade Program” \nhelps students strengthen the base for the \nupcoming Grades and explore beyond the curriculum."
                  }
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__fq8Df
                  )}
                >
                  {"About Us"}
                </div>

                <Rectangle7Icon
                  className={classNames(defaultcss.all, sty.svg__v5SK6)}
                  role={"img"}
                />

                <Rectangle7Icon
                  className={classNames(defaultcss.all, sty.svg___55YfU)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__crbzF
                  )}
                >
                  {"2Xcell for students"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__ogQN
                  )}
                >
                  {"2Xcell for school"}
                </div>

                <div
                  data-plasmic-name={"image6"}
                  data-plasmic-override={overrides.image6}
                  className={classNames(defaultcss.all, sty.image6)}
                />
              </div>
            </div>

            <div
              data-plasmic-name={"strengthSection"}
              data-plasmic-override={overrides.strengthSection}
              className={classNames(defaultcss.all, sty.strengthSection)}
            >
              <div
                data-plasmic-name={"strengthContent"}
                data-plasmic-override={overrides.strengthContent}
                className={classNames(defaultcss.all, sty.strengthContent)}
              >
                <Rectangle1519Icon
                  className={classNames(defaultcss.all, sty.svg__ortF)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"group914"}
                  data-plasmic-override={overrides.group914}
                  className={classNames(defaultcss.all, sty.group914)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__nkHj
                    )}
                  >
                    {"Our Strength in Numbers"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__dY95C
                    )}
                  >
                    {
                      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour"
                    }
                  </div>

                  <div
                    data-plasmic-name={"_1"}
                    data-plasmic-override={overrides._1}
                    className={classNames(defaultcss.all, sty._1)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__uJsOg
                      )}
                    >
                      {"50K+"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__yvVOd
                      )}
                    >
                      {"Successful Students"}
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"_2"}
                    data-plasmic-override={overrides._2}
                    className={classNames(defaultcss.all, sty._2)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__gE1Wp
                      )}
                    >
                      {"1350+"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__gtQjV
                      )}
                    >
                      {"Enroll Schools"}
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"_4"}
                    data-plasmic-override={overrides._4}
                    className={classNames(defaultcss.all, sty._4)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__bXrVk
                      )}
                    >
                      {"1820+"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__b9EGj
                      )}
                    >
                      {"Members"}
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"_3"}
                    data-plasmic-override={overrides._3}
                    className={classNames(defaultcss.all, sty._3)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__oRGp7
                      )}
                    >
                      {"650+"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__cmCi
                      )}
                    >
                      {"Expert Instructor"}
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div
              data-plasmic-name={"studentSection"}
              data-plasmic-override={overrides.studentSection}
              className={classNames(defaultcss.all, sty.studentSection)}
            >
              <div
                data-plasmic-name={"studentContent"}
                data-plasmic-override={overrides.studentContent}
                className={classNames(defaultcss.all, sty.studentContent)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__opwS
                  )}
                >
                  {"Demo 1"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox___6Mdv
                  )}
                >
                  {"Demo 2"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__nGm5G
                  )}
                >
                  {"Demo 3"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox___6A1B
                  )}
                >
                  {"Course Demo Videos"}
                </div>

                <div
                  data-plasmic-name={"browseCourses"}
                  data-plasmic-override={overrides.browseCourses}
                  className={classNames(defaultcss.all, sty.browseCourses)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__kTq84
                    )}
                  >
                    {"Browse Course"}
                  </div>

                  <Rectangle10Icon
                    className={classNames(defaultcss.all, sty.svg__zbv6X)}
                    role={"img"}
                  />
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__m8Va1
                  )}
                >
                  {"Air, Water and Soil"}
                </div>

                <Rectangle8Icon
                  className={classNames(defaultcss.all, sty.svg__fjte)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__yfZc5
                  )}
                >
                  {"2,526,471 Views"}
                </div>

                <div
                  data-plasmic-name={"time"}
                  data-plasmic-override={overrides.time}
                  className={classNames(defaultcss.all, sty.time)}
                >
                  <Rectangle9Icon
                    className={classNames(defaultcss.all, sty.svg__nWPo)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__fbG44
                    )}
                  >
                    {"8h 17min"}
                  </div>
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__mKjZd
                  )}
                >
                  {"Solar System"}
                </div>

                <Rectangle8Icon
                  className={classNames(defaultcss.all, sty.svg__yKrs)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__tpTyn
                  )}
                >
                  {"2,526,471 Views"}
                </div>

                <div
                  data-plasmic-name={"time2"}
                  data-plasmic-override={overrides.time2}
                  className={classNames(defaultcss.all, sty.time2)}
                >
                  <Rectangle9Icon
                    className={classNames(defaultcss.all, sty.svg__jMjyi)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__kVh68
                    )}
                  >
                    {"8h 17min"}
                  </div>
                </div>

                <div
                  data-plasmic-name={"maskGroup1"}
                  data-plasmic-override={overrides.maskGroup1}
                  className={classNames(defaultcss.all, sty.maskGroup1)}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__c0Ds1
                  )}
                >
                  {"Planets and Solar System"}
                </div>

                <Rectangle8Icon
                  className={classNames(defaultcss.all, sty.svg__gb3Tn)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__v6W
                  )}
                >
                  {"2,526,471 Views"}
                </div>

                <div
                  data-plasmic-name={"time3"}
                  data-plasmic-override={overrides.time3}
                  className={classNames(defaultcss.all, sty.time3)}
                >
                  <Rectangle9Icon
                    className={classNames(defaultcss.all, sty.svg___7CIse)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__jLLd6
                    )}
                  >
                    {"8h 17min"}
                  </div>
                </div>

                <div
                  data-plasmic-name={"grade1"}
                  data-plasmic-override={overrides.grade1}
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.grade1
                  )}
                >
                  {"Grade 1     "}
                </div>

                <div
                  data-plasmic-name={"grade2"}
                  data-plasmic-override={overrides.grade2}
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.grade2
                  )}
                >
                  {"Grade 1     "}
                </div>

                <div
                  data-plasmic-name={"grade3"}
                  data-plasmic-override={overrides.grade3}
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.grade3
                  )}
                >
                  {"Grade 1     "}
                </div>

                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img___3WQfB)}
                  role={"img"}
                  src={"/plasmic/2_xcell_landing_page/images/rectangle21.svg"}
                />

                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__gTxA)}
                  role={"img"}
                  src={"/plasmic/2_xcell_landing_page/images/rectangle162.svg"}
                />

                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img___5Po1D)}
                  role={"img"}
                  src={"/plasmic/2_xcell_landing_page/images/rectangle160.svg"}
                />

                <div
                  data-plasmic-name={"palyIcon"}
                  data-plasmic-override={overrides.palyIcon}
                  className={classNames(defaultcss.all, sty.palyIcon)}
                >
                  <Ellipse2Icon
                    className={classNames(defaultcss.all, sty.svg__qXNM)}
                    role={"img"}
                  />

                  <Polygon1Icon
                    className={classNames(defaultcss.all, sty.svg___2MGaD)}
                    role={"img"}
                  />
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox___2AsUl
                  )}
                >
                  {"Preview Course"}
                </div>

                <div
                  data-plasmic-name={"palyIcon2"}
                  data-plasmic-override={overrides.palyIcon2}
                  className={classNames(defaultcss.all, sty.palyIcon2)}
                >
                  <Ellipse2Icon
                    className={classNames(defaultcss.all, sty.svg__gS8B9)}
                    role={"img"}
                  />

                  <Polygon1Icon
                    className={classNames(defaultcss.all, sty.svg__aGlV0)}
                    role={"img"}
                  />
                </div>

                <Rectangle1575Icon
                  className={classNames(defaultcss.all, sty.svg___3ZUlU)}
                  role={"img"}
                />

                <Rectangle1575Icon
                  className={classNames(defaultcss.all, sty.svg__ecKuC)}
                  role={"img"}
                />

                <Rectangle1576Icon
                  className={classNames(defaultcss.all, sty.svg__hkOaI)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"image7"}
                  data-plasmic-override={overrides.image7}
                  className={classNames(defaultcss.all, sty.image7)}
                />
              </div>
            </div>

            <footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames(defaultcss.all, sty.footer)}
            >
              <div
                data-plasmic-name={"footerContent"}
                data-plasmic-override={overrides.footerContent}
                className={classNames(defaultcss.all, sty.footerContent)}
              >
                <Rectangle11Icon
                  className={classNames(defaultcss.all, sty.svg__ey6Gk)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"commuinity"}
                  data-plasmic-override={overrides.commuinity}
                  className={classNames(defaultcss.all, sty.commuinity)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__tZhq5
                    )}
                  >
                    {"Commuinity"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__i8Evo
                    )}
                  >
                    {"Create Account"}
                  </div>
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__ksNqJ
                  )}
                >
                  {
                    "Terms  Condition\n\nPrivacy & Policy\n\nCopyright Issue\n\nGet Help"
                  }
                </div>

                <div
                  data-plasmic-name={"joinUs"}
                  data-plasmic-override={overrides.joinUs}
                  className={classNames(defaultcss.all, sty.joinUs)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__tqU0
                    )}
                  >
                    {"Join Us"}
                  </div>

                  <div
                    data-plasmic-name={"studentSchoolsContactUsCareer"}
                    data-plasmic-override={
                      overrides.studentSchoolsContactUsCareer
                    }
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.studentSchoolsContactUsCareer
                    )}
                  >
                    {"Student\n\nSchools\n\nContact Us\n\nCareer "}
                  </div>
                </div>

                <Rectangle1577Icon
                  className={classNames(defaultcss.all, sty.svg__a8DPh)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"group926"}
                  data-plasmic-override={overrides.group926}
                  className={classNames(defaultcss.all, sty.group926)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__hcOmA
                    )}
                  >
                    {""}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox___0U38U
                    )}
                  >
                    {"Apple IOs"}
                  </div>
                </div>

                <Rectangle1578Icon
                  className={classNames(defaultcss.all, sty.svg___6RHg)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"group927"}
                  data-plasmic-override={overrides.group927}
                  className={classNames(defaultcss.all, sty.group927)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__oh7Sh
                    )}
                  >
                    {""}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__vGMrS
                    )}
                  >
                    {"Google Play"}
                  </div>
                </div>

                <Line207Icon
                  className={classNames(defaultcss.all, sty.svg__zXlUo)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__dNnQf
                  )}
                >
                  {"Copyright ©  2010-2019 2xCELL"}
                </div>

                <div
                  data-plasmic-name={"instagramLogoPng6023F9Ae0Feb9680X680"}
                  data-plasmic-override={
                    overrides.instagramLogoPng6023F9Ae0Feb9680X680
                  }
                  className={classNames(
                    defaultcss.all,
                    sty.instagramLogoPng6023F9Ae0Feb9680X680
                  )}
                />

                <div
                  data-plasmic-name={"socialLinkedinCircle512"}
                  data-plasmic-override={overrides.socialLinkedinCircle512}
                  className={classNames(
                    defaultcss.all,
                    sty.socialLinkedinCircle512
                  )}
                />

                <div
                  data-plasmic-name={"image8"}
                  data-plasmic-override={overrides.image8}
                  className={classNames(defaultcss.all, sty.image8)}
                />
              </div>
            </footer>
          </main>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navBar",
    "navContent",
    "logo",
    "navLinks",
    "home",
    "contactUs",
    "blog",
    "_2XCellForStudents",
    "demo",
    "mainContent",
    "heroContent",
    "illustration",
    "group3",
    "why2Xcell",
    "why2XcellContent",
    "btn",
    "btn2",
    "aboutSection",
    "aboutContent",
    "btn3",
    "image6",
    "strengthSection",
    "strengthContent",
    "group914",
    "_1",
    "_2",
    "_4",
    "_3",
    "studentSection",
    "studentContent",
    "browseCourses",
    "time",
    "time2",
    "maskGroup1",
    "time3",
    "grade1",
    "grade2",
    "grade3",
    "palyIcon",
    "palyIcon2",
    "image7",
    "footer",
    "footerContent",
    "commuinity",
    "joinUs",
    "studentSchoolsContactUsCareer",
    "group926",
    "group927",
    "instagramLogoPng6023F9Ae0Feb9680X680",
    "socialLinkedinCircle512",
    "image8"
  ],
  navBar: [
    "navBar",
    "navContent",
    "logo",
    "navLinks",
    "home",
    "contactUs",
    "blog",
    "_2XCellForStudents",
    "demo"
  ],
  navContent: [
    "navContent",
    "logo",
    "navLinks",
    "home",
    "contactUs",
    "blog",
    "_2XCellForStudents",
    "demo"
  ],
  logo: ["logo"],
  navLinks: [
    "navLinks",
    "home",
    "contactUs",
    "blog",
    "_2XCellForStudents",
    "demo"
  ],
  home: ["home"],
  contactUs: ["contactUs"],
  blog: ["blog"],
  _2XCellForStudents: ["_2XCellForStudents"],
  demo: ["demo"],
  mainContent: [
    "mainContent",
    "heroContent",
    "illustration",
    "group3",
    "why2Xcell",
    "why2XcellContent",
    "btn",
    "btn2",
    "aboutSection",
    "aboutContent",
    "btn3",
    "image6",
    "strengthSection",
    "strengthContent",
    "group914",
    "_1",
    "_2",
    "_4",
    "_3",
    "studentSection",
    "studentContent",
    "browseCourses",
    "time",
    "time2",
    "maskGroup1",
    "time3",
    "grade1",
    "grade2",
    "grade3",
    "palyIcon",
    "palyIcon2",
    "image7",
    "footer",
    "footerContent",
    "commuinity",
    "joinUs",
    "studentSchoolsContactUsCareer",
    "group926",
    "group927",
    "instagramLogoPng6023F9Ae0Feb9680X680",
    "socialLinkedinCircle512",
    "image8"
  ],
  heroContent: ["heroContent", "illustration", "group3"],
  illustration: ["illustration", "group3"],
  group3: ["group3"],
  why2Xcell: ["why2Xcell", "why2XcellContent", "btn", "btn2"],
  why2XcellContent: ["why2XcellContent", "btn", "btn2"],
  btn: ["btn"],
  btn2: ["btn2"],
  aboutSection: ["aboutSection", "aboutContent", "btn3", "image6"],
  aboutContent: ["aboutContent", "btn3", "image6"],
  btn3: ["btn3"],
  image6: ["image6"],
  strengthSection: [
    "strengthSection",
    "strengthContent",
    "group914",
    "_1",
    "_2",
    "_4",
    "_3"
  ],
  strengthContent: ["strengthContent", "group914", "_1", "_2", "_4", "_3"],
  group914: ["group914", "_1", "_2", "_4", "_3"],
  _1: ["_1"],
  _2: ["_2"],
  _4: ["_4"],
  _3: ["_3"],
  studentSection: [
    "studentSection",
    "studentContent",
    "browseCourses",
    "time",
    "time2",
    "maskGroup1",
    "time3",
    "grade1",
    "grade2",
    "grade3",
    "palyIcon",
    "palyIcon2",
    "image7"
  ],
  studentContent: [
    "studentContent",
    "browseCourses",
    "time",
    "time2",
    "maskGroup1",
    "time3",
    "grade1",
    "grade2",
    "grade3",
    "palyIcon",
    "palyIcon2",
    "image7"
  ],
  browseCourses: ["browseCourses"],
  time: ["time"],
  time2: ["time2"],
  maskGroup1: ["maskGroup1"],
  time3: ["time3"],
  grade1: ["grade1"],
  grade2: ["grade2"],
  grade3: ["grade3"],
  palyIcon: ["palyIcon"],
  palyIcon2: ["palyIcon2"],
  image7: ["image7"],
  footer: [
    "footer",
    "footerContent",
    "commuinity",
    "joinUs",
    "studentSchoolsContactUsCareer",
    "group926",
    "group927",
    "instagramLogoPng6023F9Ae0Feb9680X680",
    "socialLinkedinCircle512",
    "image8"
  ],
  footerContent: [
    "footerContent",
    "commuinity",
    "joinUs",
    "studentSchoolsContactUsCareer",
    "group926",
    "group927",
    "instagramLogoPng6023F9Ae0Feb9680X680",
    "socialLinkedinCircle512",
    "image8"
  ],
  commuinity: ["commuinity"],
  joinUs: ["joinUs", "studentSchoolsContactUsCareer"],
  studentSchoolsContactUsCareer: ["studentSchoolsContactUsCareer"],
  group926: ["group926"],
  group927: ["group927"],
  instagramLogoPng6023F9Ae0Feb9680X680: [
    "instagramLogoPng6023F9Ae0Feb9680X680"
  ],
  socialLinkedinCircle512: ["socialLinkedinCircle512"],
  image8: ["image8"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  navBar: "nav";
  navContent: "div";
  logo: "img";
  navLinks: "div";
  home: "div";
  contactUs: "div";
  blog: "div";
  _2XCellForStudents: "div";
  demo: "div";
  mainContent: "main";
  heroContent: "div";
  illustration: "div";
  group3: "div";
  why2Xcell: "div";
  why2XcellContent: "div";
  btn: "button";
  btn2: "div";
  aboutSection: "div";
  aboutContent: "div";
  btn3: "div";
  image6: "div";
  strengthSection: "div";
  strengthContent: "div";
  group914: "div";
  _1: "div";
  _2: "div";
  _4: "div";
  _3: "div";
  studentSection: "div";
  studentContent: "div";
  browseCourses: "div";
  time: "div";
  time2: "div";
  maskGroup1: "div";
  time3: "div";
  grade1: "div";
  grade2: "div";
  grade3: "div";
  palyIcon: "div";
  palyIcon2: "div";
  image7: "div";
  footer: "footer";
  footerContent: "div";
  commuinity: "div";
  joinUs: "div";
  studentSchoolsContactUsCareer: "div";
  group926: "div";
  group927: "div";
  instagramLogoPng6023F9Ae0Feb9680X680: "div";
  socialLinkedinCircle512: "div";
  image8: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLandingPage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLandingPage__VariantsArgs;
    args?: PlasmicLandingPage__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicLandingPage__Fetches;
  } & Omit<PlasmicLandingPage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicLandingPage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicLandingPage__ArgProps,
      internalVariantPropNames: PlasmicLandingPage__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicLandingPage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLandingPage";
  } else {
    func.displayName = `PlasmicLandingPage.${nodeName}`;
  }
  return func;
}

export const PlasmicLandingPage = Object.assign(
  // Top-level PlasmicLandingPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    navContent: makeNodeComponent("navContent"),
    logo: makeNodeComponent("logo"),
    navLinks: makeNodeComponent("navLinks"),
    home: makeNodeComponent("home"),
    contactUs: makeNodeComponent("contactUs"),
    blog: makeNodeComponent("blog"),
    _2XCellForStudents: makeNodeComponent("_2XCellForStudents"),
    demo: makeNodeComponent("demo"),
    mainContent: makeNodeComponent("mainContent"),
    heroContent: makeNodeComponent("heroContent"),
    illustration: makeNodeComponent("illustration"),
    group3: makeNodeComponent("group3"),
    why2Xcell: makeNodeComponent("why2Xcell"),
    why2XcellContent: makeNodeComponent("why2XcellContent"),
    btn: makeNodeComponent("btn"),
    btn2: makeNodeComponent("btn2"),
    aboutSection: makeNodeComponent("aboutSection"),
    aboutContent: makeNodeComponent("aboutContent"),
    btn3: makeNodeComponent("btn3"),
    image6: makeNodeComponent("image6"),
    strengthSection: makeNodeComponent("strengthSection"),
    strengthContent: makeNodeComponent("strengthContent"),
    group914: makeNodeComponent("group914"),
    _1: makeNodeComponent("_1"),
    _2: makeNodeComponent("_2"),
    _4: makeNodeComponent("_4"),
    _3: makeNodeComponent("_3"),
    studentSection: makeNodeComponent("studentSection"),
    studentContent: makeNodeComponent("studentContent"),
    browseCourses: makeNodeComponent("browseCourses"),
    time: makeNodeComponent("time"),
    time2: makeNodeComponent("time2"),
    maskGroup1: makeNodeComponent("maskGroup1"),
    time3: makeNodeComponent("time3"),
    grade1: makeNodeComponent("grade1"),
    grade2: makeNodeComponent("grade2"),
    grade3: makeNodeComponent("grade3"),
    palyIcon: makeNodeComponent("palyIcon"),
    palyIcon2: makeNodeComponent("palyIcon2"),
    image7: makeNodeComponent("image7"),
    footer: makeNodeComponent("footer"),
    footerContent: makeNodeComponent("footerContent"),
    commuinity: makeNodeComponent("commuinity"),
    joinUs: makeNodeComponent("joinUs"),
    studentSchoolsContactUsCareer: makeNodeComponent(
      "studentSchoolsContactUsCareer"
    ),
    group926: makeNodeComponent("group926"),
    group927: makeNodeComponent("group927"),
    instagramLogoPng6023F9Ae0Feb9680X680: makeNodeComponent(
      "instagramLogoPng6023F9Ae0Feb9680X680"
    ),
    socialLinkedinCircle512: makeNodeComponent("socialLinkedinCircle512"),
    image8: makeNodeComponent("image8"),

    // Metadata about props expected for PlasmicLandingPage
    internalVariantProps: PlasmicLandingPage__VariantProps,
    internalArgProps: PlasmicLandingPage__ArgProps
  }
);

export default PlasmicLandingPage;
/* prettier-ignore-end */
